### ISSUE TITLE
upd

### ISSUE THREAD

**Issue by dyadyaweb** [JingShing/dark_and_darker_bard#2]
The script affects fps (-40fps) as it runs in an infinite loop.
On resolution 2560x1440 the script works with 60% chance, with modified images.
I may have set the wrong points - 980,1025,1600,1250

**Comment by JingShing** [comment]
I think your position is way too big. Maybe reduce the area can help?
Because my screen is smaller than yours. So I take less time to run the script. But infinite loop truly a problem.
I may fixed that in future version.

And for the other problem:
Here is the [script help you to get position](https://github.com/JingShing/dark_and_darker_bard/blob/main/helping_script/get_position.py).

And 4 value is x, y, width, height.
You should get the left top pos(x1, y1) and right down pos(x2, y2).
And value should be x1,y1,(x2-x1),(y2-y1)

Thanks for your issue. If there still some problems it is welcome for you to comment.

**Comment by gwendolynemaxinegwenstacy** [comment]
region=1023,1146,515,24 for 2k screen
